name: Auto Crosspost

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update:
    name: Crosspost
    runs-on: ubuntu-latest
    env:
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
      MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run crosspost
        run: python crosspost.py
  
      - name: Commit database changes
        run: |
          if git diff --name-only db/database.json db/post.cache | grep . ; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add db
            git commit -m "update database" db
            git push
          fi

